version: '3.7'

services:

  ## Build MySQL first
  mysqldb:
    image: mysql:5.7
    restart: always
    ## When the official MySQL container is started for the first time, a new database will be created first.
    ## Then it will execute files with extensions .sh, init.sql and init.sql.gz that are found in /docker-entrypoint-initdb.d
    command: --init-file /data/application/init.sql
    volumes:
      - ./db/init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=treadstone
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    networks:
      - treadstone-mysql

  ## Requires MySQL or will not start
  ## Uses the Dockerfile in the root
  microservice:
    depends_on:
      - mysqldb
    build: .
    image: seanjgildea/springbootkubernetes
    ports:
      - 8043:8080
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=treadstone
      - some.value=This is Sparta!!!
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/treadstone?autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - treadstone-mysql
    volumes:
      - microservice-logs:/opt/com/treadstone_system/logs

volumes:
  microservice-logs:

networks:
  treadstone-mysql: