version: '3.7'

services:
  java:
    build: .
    depends_on:
      - db
    ports:
      - 8043:8080
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=treadstone
      - some.value=This is Sparta!!!

  db:
    image: mysql:5.7
    ports: 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=treadstone
      - MYSQL_PASSWORD=password
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: