version: '3.7'

services:
  java:
    build: .
    depends_on:
      - mysqldb
    ports:
      - 8043:8080
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=treadstone
      - some.value=This is Sparta!!!
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/treadstone?autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - treadstone-mysql

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=treadstone
      - MYSQL_PASSWORD=password
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - treadstone-mysql

volumes:
  my-db:

networks:
  treadstone-mysql: