spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/treadstone
    username: root
    initialization-mode: always # needed to load data.sql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

some:
  value: default template value

server:
  port: 8080

springfox:
  documentation:
    auto-startup: true

swagger:
  title: Spring Boot for Kubernetes Demo
  description: Containerized microservice for Docker/Kubernetes
  version: 1.0
  termsOfServiceUrl:
  license:
  licenseUrl:
  contact:
    name: Sean Gildea
    email: sgildea@github.com
    url: http://example.com