# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: seanjgildea/springbootkubernetes
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: treadstone
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    working_directory: ~/tmp

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            sleep 5

      - run: mvn dependency:go-offline

      # run tests!
      - run: mvn integration-test